---
# This playbook contains common plays that will be run on all nodes.

# - name: Print all available facts
#   ansible.builtin.debug:
#     var: ansible_facts

- name: Print SELinux status if available
  ansible.builtin.debug:
    var: sestatus
  when: sestatus is defined
