---
# Common handlers

- name: restart_dhcp
  ansible.builtin.systemd_service:
    state: restarted
    name: dnsmasq.service
  run_once: true
  delegate_to: "{{ dhcp_server }}"

- name: activate_selinux
  command: selinux-activate

- name: reboot_host
  ansible.builtin.reboot:
