---
# This playbook deploys VMs

- name: Check VM Host availability and prep
  hosts: vmhosts
  remote_user: garrettj
  become: yes
  # gather_facts: yes
  gather_facts: no  # Speed up debugging
  tags: prep

  roles:
    - prep_hosts

- name: Deploy the VMs
  hosts: vmguests
  remote_user: garrettj
  become: yes
  # remote_user: root
  # become: no
  gather_facts: no
  tags: deploy

  roles:
    - create_guests

- name: Print final messages
  hosts: all
  remote_user: garrettj
  gather_facts: no
  tags: always

  roles:
    - end_messages
